// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBhAcK-fm7g8_AFqckVipiL__FH0I16gI',
    appId: '1:775977915206:web:7db87c58b0d9f72b97cb47',
    messagingSenderId: '775977915206',
    projectId: 'future-graph-411205',
    authDomain: 'future-graph-411205.firebaseapp.com',
    storageBucket: 'future-graph-411205.appspot.com',
    measurementId: 'G-S3XVH5NWBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGkBcaF98c0R0ttVtQIw59MIZTMCpCLw',
    appId: '1:775977915206:android:0e644b748d0de97797cb47',
    messagingSenderId: '775977915206',
    projectId: 'future-graph-411205',
    storageBucket: 'future-graph-411205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAd2pokHnpatDm7n723LupC8SylFiM2zk',
    appId: '1:775977915206:ios:92abe724358cb59297cb47',
    messagingSenderId: '775977915206',
    projectId: 'future-graph-411205',
    storageBucket: 'future-graph-411205.appspot.com',
    iosBundleId: 'com.example.plantDiseaseClassifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAd2pokHnpatDm7n723LupC8SylFiM2zk',
    appId: '1:775977915206:ios:529011dabf078ef697cb47',
    messagingSenderId: '775977915206',
    projectId: 'future-graph-411205',
    storageBucket: 'future-graph-411205.appspot.com',
    iosBundleId: 'com.example.plantDiseaseClassifier.RunnerTests',
  );
}
